// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: slot.proto

package slotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	RoundId       string                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Uid           uint64                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	AgentId       uint32                 `protobuf:"varint,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	GameId        uint32                 `protobuf:"varint,6,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	BetAmount     int64                  `protobuf:"varint,7,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	DebugFail     bool                   `protobuf:"varint,99,opt,name=debug_fail,json=debugFail,proto3" json:"debug_fail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinReq) Reset() {
	*x = SpinReq{}
	mi := &file_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinReq) ProtoMessage() {}

func (x *SpinReq) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinReq.ProtoReflect.Descriptor instead.
func (*SpinReq) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{0}
}

func (x *SpinReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SpinReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SpinReq) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SpinReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SpinReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SpinReq) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SpinReq) GetBetAmount() int64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *SpinReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SpinReq) GetDebugFail() bool {
	if x != nil {
		return x.DebugFail
	}
	return false
}

type SpinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	WinAmount     int64                  `protobuf:"varint,3,opt,name=win_amount,json=winAmount,proto3" json:"win_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinResp) Reset() {
	*x = SpinResp{}
	mi := &file_slot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinResp) ProtoMessage() {}

func (x *SpinResp) ProtoReflect() protoreflect.Message {
	mi := &file_slot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinResp.ProtoReflect.Descriptor instead.
func (*SpinResp) Descriptor() ([]byte, []int) {
	return file_slot_proto_rawDescGZIP(), []int{1}
}

func (x *SpinResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SpinResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SpinResp) GetWinAmount() int64 {
	if x != nil {
		return x.WinAmount
	}
	return 0
}

var File_slot_proto protoreflect.FileDescriptor

const file_slot_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"slot.proto\x12\x04slot\"\xfe\x01\n" +
	"\aSpinReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\tR\aroundId\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x04R\x03uid\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\rR\aagentId\x12\x17\n" +
	"\agame_id\x18\x06 \x01(\rR\x06gameId\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\a \x01(\x03R\tbetAmount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"debug_fail\x18c \x01(\bR\tdebugFail\"^\n" +
	"\bSpinResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x1d\n" +
	"\n" +
	"win_amount\x18\x03 \x01(\x03R\twinAmountB\x1eZ\x1cgame-api/proto/slotpb;slotpbb\x06proto3"

var (
	file_slot_proto_rawDescOnce sync.Once
	file_slot_proto_rawDescData []byte
)

func file_slot_proto_rawDescGZIP() []byte {
	file_slot_proto_rawDescOnce.Do(func() {
		file_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)))
	})
	return file_slot_proto_rawDescData
}

var file_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_slot_proto_goTypes = []any{
	(*SpinReq)(nil),  // 0: slot.SpinReq
	(*SpinResp)(nil), // 1: slot.SpinResp
}
var file_slot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slot_proto_init() }
func file_slot_proto_init() {
	if File_slot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slot_proto_rawDesc), len(file_slot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slot_proto_goTypes,
		DependencyIndexes: file_slot_proto_depIdxs,
		MessageInfos:      file_slot_proto_msgTypes,
	}.Build()
	File_slot_proto = out.File
	file_slot_proto_goTypes = nil
	file_slot_proto_depIdxs = nil
}
