// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wallet.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家ID
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 代理ID
	AgentId       uint32 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceReq) Reset() {
	*x = BalanceReq{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceReq) ProtoMessage() {}

func (x *BalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceReq.ProtoReflect.Descriptor instead.
func (*BalanceReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BalanceReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type BalanceResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 钱包余额（最小货币单位）
	Balance uint64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// 币别
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResp) Reset() {
	*x = BalanceResp{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResp) ProtoMessage() {}

func (x *BalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResp.ProtoReflect.Descriptor instead.
func (*BalanceResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceResp) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RollbackReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家ID
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 代理ID
	AgentId uint32 `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// 原下注单号
	OrderNo string `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 幂等请求ID
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 回滚类型
	RollbackType int32 `protobuf:"varint,5,opt,name=rollback_type,json=rollbackType,proto3" json:"rollback_type,omitempty"`
	// 回滚原因（可选）
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackReq) Reset() {
	*x = RollbackReq{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReq) ProtoMessage() {}

func (x *RollbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReq.ProtoReflect.Descriptor instead.
func (*RollbackReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *RollbackReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RollbackReq) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RollbackReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RollbackReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RollbackReq) GetRollbackType() int32 {
	if x != nil {
		return x.RollbackType
	}
	return 0
}

func (x *RollbackReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RollbackResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 回滚后余额
	Balance       uint64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResp) Reset() {
	*x = RollbackResp{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResp) ProtoMessage() {}

func (x *RollbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResp.ProtoReflect.Descriptor instead.
func (*RollbackResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackResp) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\"9\n" +
	"\n" +
	"BalanceReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\rR\aagentId\"C\n" +
	"\vBalanceResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xb1\x01\n" +
	"\vRollbackReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\rR\aagentId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12#\n" +
	"\rrollback_type\x18\x05 \x01(\x05R\frollbackType\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"(\n" +
	"\fRollbackResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalanceB\"Z game-api/proto/walletpb;walletpbb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wallet_proto_goTypes = []any{
	(*BalanceReq)(nil),   // 0: wallet.BalanceReq
	(*BalanceResp)(nil),  // 1: wallet.BalanceResp
	(*RollbackReq)(nil),  // 2: wallet.RollbackReq
	(*RollbackResp)(nil), // 3: wallet.RollbackResp
}
var file_wallet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
